version: '3.3'
services:
    ftp-server:
       container_name: ftp_server
       environment:
           - FTP_PASS=123
           - FTP_USER=user
       image: garethflowers/ftp-server
       expose:
           - "20-21/tcp"
           - "40000-40009/tcp"
       volumes:
           - "/data:/home/user"
       networks:
           - backend

    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - backend

    mlflow:
        restart: always
        build: .
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            - db
        ports:
            - "5000:5000"
        expose:
            - "5000"
        networks:
            - backend
            - frontend
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --serve-artifacts --host 0.0.0.0 --artifacts-destination ftp://user:123@ftp-server/
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    dbdata:
